const fs = require('fs');
const path = require('path');

class TestScriptGenerator {
  constructor(outputDir = 'generated_tests') {
    this.outputDir = path.resolve(process.cwd(), outputDir);
    if (!fs.existsSync(this.outputDir)) {
      fs.mkdirSync(this.outputDir, { recursive: true });
    }
  }

  generate(actions, testName = 'ai_generated') {
    const timestamp = Date.now();
    const filename = `${testName}_${timestamp}.spec.ts`;
    
    let script = `import { test, expect } from '@playwright/test';\n\n`;
    script += `test('Autogenerated AI Test - ${timestamp}', async ({ page }) => {\n`;
    
    for (const action of actions) {
      if (action.action === 'fill') {
        script += `  await page.locator('${action.selector}').fill('${action.value}');\n`;
      } else if (action.action === 'click') {
        script += `  await page.locator('${action.selector}').click();\n`;
      } else if (action.action === 'wait') {
        script += `  await page.waitForTimeout(${action.value || 2000});\n`;
      } else if (action.action === 'goto') {
        script += `  await page.goto('${action.value}');\n`;
      }
    }
    
    script += `});\n`;

    const filepath = path.join(this.outputDir, filename);
    fs.writeFileSync(filepath, script, 'utf8');
    return filepath;
  }
}

module.exports = TestScriptGenerator;
