import { test, expect } from '@playwright/test';

test('Autogenerated AI Test - 1791225379910', async ({ page }) => {
  await page.locator('#theme-toggle').click();
  await page.locator('.hamburger').click();
  await page.locator('.sidebar-toggle').click();
  await page.locator('.bell-button').click();
  await page.locator('.btn-logout').click();
});
