import { test, expect } from '@playwright/test';

test('Autogenerated AI Test - 1791219819650', async ({ page }) => {
  await page.locator('#email').fill('gerente@ilco.com');
  await page.locator('#password').fill('password');
  await page.locator('button').click();
});
