import { test, expect } from '@playwright/test';

test('Autogenerated AI Test - 1791230798387', async ({ page }) => {
  await page.locator('#email').fill('admin@ilco.com');
  await page.locator('#password').fill('password');
  await page.locator('.btn-submit').click();
});
