import { test, expect } from '@playwright/test';

test('Autogenerated AI Test - 1791221771748', async ({ page }) => {
  await page.locator('#email').fill('gerente@ilco.com');
  await page.locator('#password').fill('password');
  await page.locator('text=Iniciar sesión').click();
});
