import { test, expect } from '@playwright/test';

test('Autogenerated AI Test - 1791219454709', async ({ page }) => {
  await page.locator('#email').fill('test@example.com');
  await page.locator('#password').fill('Test Value');
  await page.locator('button').click();
});
